### ISSUE TITLE
好用

### ISSUE THREAD

**Issue by nonlinearthink** [HDsky/A-batchfile-for-ZUCC#1]
之前用官网VPN，后来卸载后内网直接上不去，一直没办法解决，向大佬低头。

**Comment by HDsky** [comment]
所以现在有什么问题呢0.0（理论上这里是提建议和问题的地方～）

**Comment by nonlinearthink** [comment]
> 所以现在有什么问题呢0.0（理论上这里是提建议和问题的地方～）

我建议能不能出一个Linux版的。Linux我之前一直是用手机热点的，移动校园有线网和无线都不知道怎么连。

**Comment by HDsky** [comment]
额，好像你使用的方式和我所描述的不太一致，这个脚本的作用在于，使用电信/移动/联通的客户端连接成功后，可以访问外网，但这时候不能连接内网网站；再执行这个脚本，实现内网和外网同时访问。

**Comment by HDsky** [comment]
> > 所以现在有什么问题呢0.0（理论上这里是提建议和问题的地方～）
> 
> 我建议能不能出一个Linux版的。Linux我之前一直是用手机热点的，移动校园有线网和无线都不知道怎么连。

针对这个，建议是使用路由器作为连接方式，一般路由器上都带有L2TP拨号的～
